# Reference: https://github.com/MindStrongHealth/pre-commit-hooks/blob/master/mindstrong_node_hook_formatting/package.json#L9
# NOTE: Keep in sync with the above reference package.json definition.
bracketSpacing: false
printWidth: 115
tabWidth: 4
semi: true
singleQuote: true
trailingComma: 'es5'
arrowParens: always
